name: modern_scientific_programming
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - scipy
  - pandas
  - altair
  - vega_datasets
  - seaborn
  - openpyxl
  - statsmodels
  - scikit-learn
